const bikes=[{id:1,brand:"Yamaha",model:"MT-15",type:"Sport",pricePerHour:12,pricePerDay:84,rating:4.9,reviews:128,engine:"155 cc",available:true},{id:2,brand:"Royal Enfield",model:"Classic 350",type:"Classic",pricePerHour:15,pricePerDay:105,rating:4.8,reviews:214,engine:"349 cc",available:true},{id:3,brand:"KTM",model:"Duke 390",type:"Sport",pricePerHour:19,pricePerDay:135,rating:4.9,reviews:176,engine:"373 cc",available:true},{id:4,brand:"Royal Enfield",model:"Himalayan",type:"Adventure",pricePerHour:18,pricePerDay:126,rating:4.7,reviews:93,engine:"411 cc",available:true},{id:5,brand:"Honda",model:"CB350",type:"Classic",pricePerHour:15,pricePerDay:99,rating:4.8,reviews:145,engine:"348 cc",available:true},{id:6,brand:"Kawasaki",model:"Ninja 400",type:"Sport",pricePerHour:23,pricePerDay:160,rating:4.9,reviews:81,engine:"399 cc",available:false},{id:7,brand:"Yamaha",model:"R15 V4",type:"Sport",pricePerHour:17,pricePerDay:118,rating:4.7,reviews:117,engine:"155 cc",available:true},{id:8,brand:"Bajaj",model:"Dominar 400",type:"Cruiser",pricePerHour:16,pricePerDay:112,rating:4.6,reviews:74,engine:"373 cc",available:true},{id:9,brand:"Vespa",model:"SXL 150",type:"Scooter",pricePerHour:11,pricePerDay:77,rating:4.6,reviews:62,engine:"150 cc",available:true},{id:10,brand:"Triumph",model:"Street Twin",type:"Cruiser",pricePerHour:25,pricePerDay:175,rating:4.9,reviews:57,engine:"900 cc",available:false}];
const key={fav:"rr_favorites",book:"rr_bookings",theme:"rr_theme"};
let favorites=JSON.parse(localStorage.getItem(key.fav)||"[]"),bookings=JSON.parse(localStorage.getItem(key.book)||"[]"),activeBike=null;
const $=selector=>document.querySelector(selector), $$=selector=>[...document.querySelectorAll(selector)];
const money=value=>`$${Number(value).toLocaleString()}`, toastMessage=message=>{const toast=$("#toast");toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2400)};
function saveState(){localStorage.setItem(key.fav,JSON.stringify(favorites));localStorage.setItem(key.book,JSON.stringify(bookings))}
function cardTemplate(bike){const liked=favorites.includes(bike.id);return `<article class="bike-card"><div class="bike-image"><button class="bike-heart ${liked?"active":""}" data-fav="${bike.id}">${liked?"♥":"♡"}</button><span class="bike-mini">${bike.brand.toUpperCase()}<br>${bike.model.toUpperCase()}</span></div><div class="bike-info"><div class="bike-meta"><span>${bike.type}</span><span class="bike-rating">★ ${bike.rating} <span>(${bike.reviews})</span></span></div><h3>${bike.brand} ${bike.model}</h3><div class="bike-price"><strong>${money(bike.pricePerDay)} <small>/ day</small></strong><span class="status ${bike.available?"":"cancelled"}">${bike.available?"Available":"Booked"}</span></div><div class="bike-card-actions"><button class="outline-btn" data-details="${bike.id}">View details</button><button class="dark-btn" data-rent="${bike.id}">Rent now</button></div></div></article>`}
function renderCards(list,target){$(target).innerHTML=list.length?list.map(cardTemplate).join(""):`<div class="empty-state"><strong>No bikes found</strong>Try changing your filters or search term.</div>`}
function renderExplore(){const query=$("#bikeSearch").value.toLowerCase(),type=$("#typeFilter").value,brand=$("#brandFilter").value,max=Number($("#priceFilter").value),available=$("#availableFilter").checked;let list=bikes.filter(b=>(`${b.brand} ${b.model}`.toLowerCase().includes(query))&&(type==="all"||b.type===type)&&(brand==="all"||b.brand===brand)&&b.pricePerDay<=max&&(!available||b.available));const sort=$("#sortFilter").value;if(sort==="low")list.sort((a,b)=>a.pricePerDay-b.pricePerDay);if(sort==="high")list.sort((a,b)=>b.pricePerDay-a.pricePerDay);if(sort==="rating")list.sort((a,b)=>b.rating-a.rating);$("#resultCount").textContent=`${list.length} bike${list.length!==1?"s":""}`;renderCards(list,"#exploreGrid")}
function renderFavorites(){renderCards(bikes.filter(b=>favorites.includes(b.id)),"#favoritesGrid");$("#favoriteCount").textContent=favorites.length}
function renderRentals(tab="all"){let list=bookings.filter(b=>tab==="all"||b.status===tab);$("#rentalsList").innerHTML=list.length?list.map(item=>{const bike=bikes.find(b=>b.id===item.bikeId);return `<article class="rental-card"><div class="rental-thumb">${bike.brand}<br>${bike.model}</div><div><h3>${bike.brand} ${bike.model}</h3><p>${item.start} → ${item.end} · ${item.location}</p><small>Booking ID ${item.id} · Booked today</small></div><div class="rental-side"><span class="status ${item.status}">${item.status}</span><strong>${money(item.total)}</strong><button class="text-link" data-cancel="${item.id}">${item.status==="upcoming"?"Cancel booking":"View booking"} →</button></div></article>`}).join(""):`<div class="empty-state"><strong>No ${tab==="all"?"":tab+" "}rentals yet</strong>Your next great ride is waiting.</div>`}
function showPage(page){$$(".page-section").forEach(section=>section.classList.remove("active"));$(`#${page}Page`).classList.add("active");$$("[data-page]").forEach(link=>link.classList.toggle("active",link.dataset.page===page));if(page==="explore")renderExplore();if(page==="favorites")renderFavorites();if(page==="rentals")renderRentals();if(page==="dashboard")renderDashboard();window.scrollTo({top:0,behavior:"smooth"})}
function openDetails(id){const bike=bikes.find(item=>item.id===id);activeBike=bike;$("#modal").innerHTML=`<button class="modal-close" data-close>×</button><span class="eyebrow">${bike.type} · ${bike.brand}</span><h2>${bike.model}</h2><p>Everything you need for a smooth, memorable ride.</p><div class="modal-bike"><div class="bike-image"><span class="bike-mini">${bike.brand}<br>${bike.model}</span></div><div><h3>${money(bike.pricePerDay)} <small>/ day</small></h3><span class="bike-rating">★ ${bike.rating} <span>(${bike.reviews} reviews)</span></span><p>${bike.engine} · Automatic · Petrol</p></div></div><div class="form-grid"><div><small class="muted">Mileage</small><h3>42 mpg</h3></div><div><small class="muted">Top speed</small><h3>118 mph</h3></div><div><small class="muted">Seat height</small><h3>31.9 in</h3></div><div><small class="muted">Tank capacity</small><h3>3.7 gal</h3></div></div><div class="modal-actions"><button class="btn outline-btn" data-fav="${bike.id}">${favorites.includes(bike.id)?"♥ Saved":"♡ Add to favorites"}</button><button class="btn btn-primary" data-rent="${bike.id}">Rent now <span>→</span></button></div>`;$("#modalBackdrop").classList.add("open")}
function openBooking(id){const bike=bikes.find(item=>item.id===id);activeBike=bike;const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);$("#modal").innerHTML=`<button class="modal-close" data-close>×</button><span class="eyebrow">Reserve your ride</span><h2>Book ${bike.model}</h2><p>Flexible dates, transparent pricing, no surprises.</p><div class="modal-bike"><div class="bike-image"><span class="bike-mini">${bike.brand}<br>${bike.model}</span></div><div><h3>${bike.brand} ${bike.model}</h3><span class="bike-rating">★ ${bike.rating} · ${money(bike.pricePerDay)} / day</span></div></div><div class="form-grid"><div class="form-group"><label>Pick-up date</label><input id="bookingStart" type="date" value="${tomorrow}"></div><div class="form-group"><label>Return date</label><input id="bookingEnd" type="date" value="${tomorrow}"></div><div class="form-group"><label>Pick-up location</label><input id="bookingLocation" value="San Francisco, CA"></div><div class="form-group"><label>Pick-up time</label><input type="time" value="09:00"></div></div><div class="form-group" style="margin-top:18px"><label>Optional add-ons</label><label class="addon-row"><span><input type="checkbox" class="addon" value="12"> Helmet</span><b>$12</b></label><label class="addon-row"><span><input type="checkbox" class="addon" value="8"> Phone holder</span><b>$8</b></label><label class="addon-row"><span><input type="checkbox" class="addon" value="20"> Extra insurance</span><b>$20</b></label></div><div class="summary" id="bookingSummary"></div><div class="modal-actions"><button class="btn outline-btn" data-close>Cancel</button><button class="btn btn-primary" id="confirmBooking">Confirm booking <span>→</span></button></div>`;$("#modalBackdrop").classList.add("open");updateBookingSummary();["bookingStart","bookingEnd"].forEach(id=>$("#"+id).addEventListener("change",updateBookingSummary));$$(".addon").forEach(input=>input.addEventListener("change",updateBookingSummary))}
function updateBookingSummary(){if(!$("#bookingSummary"))return;const start=new Date($("#bookingStart").value),end=new Date($("#bookingEnd").value),days=Math.max(1,Math.ceil((end-start)/86400000)||1),addons=$$(".addon:checked").reduce((sum,input)=>sum+Number(input.value),0),base=days*activeBike.pricePerDay,fee=Math.round((base+addons)*.08),total=base+addons+fee;$("#bookingSummary").innerHTML=`<div class="summary-row"><span>Rental · ${days} day${days>1?"s":""}</span><b>${money(base)}</b></div><div class="summary-row"><span>Add-ons</span><b>${money(addons)}</b></div><div class="summary-row"><span>Service fee</span><b>${money(fee)}</b></div><div class="summary-row total"><span>Total</span><b>${money(total)}</b></div>`;$("#confirmBooking").dataset.total=total}
function confirmBooking(){const start=$("#bookingStart").value,end=$("#bookingEnd").value,total=Number($("#confirmBooking").dataset.total);bookings.unshift({id:"RR-"+Math.floor(100000+Math.random()*899999),bikeId:activeBike.id,start,end,location:$("#bookingLocation").value,total,status:"upcoming"});saveState();$("#modalBackdrop").classList.remove("open");toastMessage("Booking confirmed! Your ride is ready.");renderRentals();renderDashboard()}
function renderDashboard(){const total=bookings.reduce((sum,item)=>sum+item.total,1248);$("#spentStat").textContent=money(total);$("#upcomingStat").textContent=bookings.filter(item=>item.status==="upcoming").length+2;$("#upcomingPreview").innerHTML=`<div class="rental-card" style="border:0;padding:18px 0 0"><div class="rental-thumb">KTM<br>DUKE 390</div><div><h3>KTM Duke 390</h3><p>Sep 11 → Sep 13 · San Francisco</p><small>RR-482901 · 2 days</small></div><div class="rental-side"><span class="status">upcoming</span><strong>$270</strong></div></div>`}
document.addEventListener("click",event=>{const target=event.target.closest("[data-page],[data-fav],[data-details],[data-rent],[data-close],[data-cancel]");if(!target)return;if(target.dataset.page){showPage(target.dataset.page);$("#menuToggle").classList.remove("open")}if(target.dataset.fav){const id=Number(target.dataset.fav);favorites.includes(id)?(favorites=favorites.filter(item=>item!==id),toastMessage("Bike removed from favorites")):(favorites.push(id),toastMessage("Bike added to favorites"));saveState();renderFavorites();renderExplore();renderCards(bikes.slice(0,4),"#popularGrid");if($("#modalBackdrop").classList.contains("open")&&activeBike)openDetails(activeBike.id)}if(target.dataset.details)openDetails(Number(target.dataset.details));if(target.dataset.rent)openBooking(Number(target.dataset.rent));if(target.dataset.close)$("#modalBackdrop").classList.remove("open");if(target.dataset.cancel){const item=bookings.find(item=>item.id===target.dataset.cancel);if(item&&confirm("Cancel this booking?")){item.status="cancelled";saveState();renderRentals();toastMessage("Booking cancelled")}}});
document.addEventListener("keydown",event=>{if(event.key==="Escape"){$("#modalBackdrop").classList.remove("open");$("#notificationPanel").classList.remove("open")}});
$("#modalBackdrop").addEventListener("click",event=>{if(event.target.id==="modalBackdrop")event.currentTarget.classList.remove("open")});
$("#themeToggle").addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem(key.theme,document.body.classList.contains("dark")?"dark":"light")});
if(localStorage.getItem(key.theme)==="dark")document.body.classList.add("dark");
$("#notificationPanel").classList.remove("open");$(".notification-trigger").addEventListener("click",()=>$("#notificationPanel").classList.toggle("open"));$("#markRead").addEventListener("click",()=>{$$(".notification-item").forEach(item=>item.classList.remove("unread"));$("#unreadCount").style.display="none"});
$("#menuToggle").addEventListener("click",()=>{$(".desktop-nav").style.display=$(".desktop-nav").style.display==="flex"?"none":"flex";$(".desktop-nav").style.position="absolute";$(".desktop-nav").style.top="70px";$(".desktop-nav").style.left="20px";$(".desktop-nav").style.right="20px";$(".desktop-nav").style.padding="20px";$(".desktop-nav").style.background="var(--surface)";$(".desktop-nav").style.borderRadius="15px";$(".desktop-nav").style.flexDirection="column";$(".desktop-nav").style.zIndex="30"});
["#bikeSearch","#typeFilter","#brandFilter","#priceFilter","#availableFilter","#sortFilter"].forEach(selector=>$(selector).addEventListener("input",renderExplore));$("#priceFilter").addEventListener("input",()=>$("#priceValue").textContent=money($("#priceFilter").value));$("#clearFilters").addEventListener("click",()=>{$("#bikeSearch").value="";$("#typeFilter").value="all";$("#brandFilter").value="all";$("#priceFilter").value=180;$("#availableFilter").checked=false;$("#priceValue").textContent="$180";renderExplore()});$("#rentalTabs").addEventListener("click",event=>{if(event.target.dataset.tab){$$(".tabs button").forEach(btn=>btn.classList.remove("active"));event.target.classList.add("active");renderRentals(event.target.dataset.tab)}});
document.addEventListener("click",event=>{const category=event.target.closest(".category-card");if(category){showPage("explore");$("#typeFilter").value=category.dataset.type;renderExplore()}});
$("#modal").addEventListener("click",event=>{if(event.target.id==="confirmBooking")confirmBooking()});
const brands=[...new Set(bikes.map(b=>b.brand))];brands.forEach(brand=>$("#brandFilter").insertAdjacentHTML("beforeend",`<option>${brand}</option>`));renderCards(bikes.slice(0,4),"#popularGrid");renderExplore();renderFavorites();renderDashboard();$("#homeStartDate").textContent=new Date().toLocaleDateString("en-US",{month:"short",day:"numeric"});
